# Generated by Django 4.1.3 on 2022-11-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
