# Generated by Django 4.1.3 on 2022-11-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_concert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='seats_to_be_used',
            field=models.IntegerField(),
        ),
    ]
