# Generated by Django 4.1.3 on 2022-11-26 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_alter_concert_seats_to_be_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_seats', models.IntegerField()),
                ('price_paid', models.IntegerField()),
                ('card_number', models.CharField(max_length=255)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.concert')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.seattype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
